name: Compiler le code, Executer le tests Unitaire, Executer les scans SAST, SCA, DAST.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Executer les tests unitaire et les tests SAST sur le code source.
    steps:
    - uses: actions/checkout@v2
    - name: Installer JDK 19
      uses: actions/setup-java@v2
      with:
        java-version:'19'
        cache :maven
    - name: Compiler avec Maven et Verifier avec SonarCloud
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=java_transcription -Dsonar.organization=java_transcription -Dsonar.host.url =https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  # security:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   name: Executer les Scan SCA sur le code source
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Identifier les vulnerablities avec Snyk
  #       uses: snyk/actions/maven@master
  #       continue-on-error: true
  #       env:
  #         SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Executer les scans DAST sur l'application Web.
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - name: Scan OWASP ZAP
  #       uses: zaproxy/action-baseline@v.0.6.1
  #       with:
  #         docker_name: 'owasp/zap2docker-stable'
  #         target: 'http://testphp.vulnweb.com'
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: '-a'
  #
